USE [master]
GO

CREATE DATABASE [atlas_staging]
 CONTAINMENT = NONE
 /*If you want your data in a custom location*/
--ON  PRIMARY 
--( NAME = N'atlas_staging', FILENAME = N'C:\Program Files\path\to\data\atlas_staging.mdf' , SIZE = 23076864KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG ON 
--( NAME = N'atlas_staging_log', FILENAME = N'C:\Program Files\path\to\data\atlas_staging_log.ldf' , SIZE = 466944KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [atlas_staging] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [atlas_staging].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [atlas_staging] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [atlas_staging] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [atlas_staging] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [atlas_staging] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [atlas_staging] SET ARITHABORT OFF 
GO

ALTER DATABASE [atlas_staging] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [atlas_staging] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [atlas_staging] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [atlas_staging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [atlas_staging] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [atlas_staging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [atlas_staging] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [atlas_staging] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [atlas_staging] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [atlas_staging] SET  DISABLE_BROKER 
GO

ALTER DATABASE [atlas_staging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [atlas_staging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [atlas_staging] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [atlas_staging] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [atlas_staging] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [atlas_staging] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [atlas_staging] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [atlas_staging] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [atlas_staging] SET  MULTI_USER 
GO

ALTER DATABASE [atlas_staging] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [atlas_staging] SET DB_CHAINING OFF 
GO

ALTER DATABASE [atlas_staging] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [atlas_staging] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [atlas_staging] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [atlas_staging] SET QUERY_STORE = OFF
GO

USE [atlas_staging]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [atlas_staging] SET  READ_WRITE 
GO

USE [atlas_staging]
GO
CREATE SCHEMA [stage]
GO

USE [atlas_staging]
GO
CREATE SCHEMA [raw]
GO
