# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
name: “CI”

on:
  push:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - name: get code
        uses: actions/checkout@v1

      - name: build
        run: |
          pip install tox poetry Sphinx Pygments furo sphinx-copybutton sphinx-inline-tabs myst-parser colorama sphinx-panels
          tox -e docs

      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build